from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO

def generate_tactical_report(payload):
    """
    Generates a professional Table-based PDF dossier (Snapshot).
    Payload should be a dict or object with:
    - symbol, price, verdict, confidence, reasoning, consensus_text, agents, timestamp
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    story = []
    
    # --- ENGLISH ONLY PDF SUPPORT ---
    import os
    import json
    
    # Use standard PDF fonts to avoid encoding issues
    font_name = 'Helvetica'
    font_name_bold = 'Helvetica-Bold'

    styles = getSampleStyleSheet()
    # Override styles with Standard font
    title_style = ParagraphStyle('TitleDossier', parent=styles['Heading1'], fontName=font_name_bold, fontSize=20, spaceAfter=20, textColor=colors.HexColor("#0f172a"))
    normal_style = ParagraphStyle('NormalDossier', parent=styles['Normal'], fontName=font_name, fontSize=10)
    heading_style = ParagraphStyle('HeadingDossier', parent=styles['Heading2'], fontName=font_name_bold, fontSize=14)
    cell_style = ParagraphStyle('CellDossier', parent=styles['Normal'], fontName=font_name, fontSize=9)
    disclaimer_style = ParagraphStyle('DisclaimerDossier', parent=styles['Normal'], fontName=font_name, fontSize=8, textColor=colors.grey)
    
    # 1. HEADER
    story.append(Paragraph(f"TACTICAL DOSSIER: {payload.symbol}", title_style))
    story.append(Paragraph(f"Generated on: {payload.timestamp[:16].replace('T', ' ')}", normal_style))
    story.append(Spacer(1, 10))
    
    # 2. MARKET SNAPSHOT
    # Try to parse consensus JSON if it's a string from Vertex
    consensus_raw = getattr(payload, 'consensus_text', "No consensus data available.")
    summary_text = consensus_raw
    global_conf = payload.confidence
    verdict = payload.verdict.upper()

    if isinstance(consensus_raw, str) and consensus_raw.strip().startswith('{'):
        try:
            c_data = json.loads(consensus_raw)
            summary_text = c_data.get('summary', consensus_raw)
            global_conf = c_data.get('global_confidence', global_conf)
            verdict = c_data.get('verdict', verdict).upper()
        except:
            pass

    price_color = colors.green if "BUY" in verdict else colors.red if "SELL" in verdict else colors.black
    
    story.append(Paragraph(f"<b>CURRENT PRICE:</b> ${payload.price:,.2f}", normal_style))
    story.append(Paragraph(f"<b>SWARM VERDICT:</b> <font color='{price_color}'>{verdict} ({global_conf}%)</font>", normal_style))
    story.append(Spacer(1, 20))
    
    # 3. EXECUTIVE SUMMARY (CONSENSUS)
    story.append(Paragraph("EXECUTIVE SUMMARY (Hive Consensus)", heading_style))
    story.append(Paragraph(summary_text, normal_style))
    story.append(Spacer(1, 20))
    
    # 4. AGENT BREAKDOWN (TABLE)
    story.append(Paragraph("DETAILED AGENT BREAKDOWN", heading_style))
    story.append(Spacer(1, 10))
    
    # Prepare details data
    # Header Row
    table_data = [['ROLE', 'SIGNAL', 'CONFIDENCE', 'REASONING']]
    
    agents = getattr(payload, 'agents', [])
    for agent in agents:
        # Handle both dict and object access if necessary, assuming dict from previous code
        if isinstance(agent, dict):
            role = agent.get('role', 'UNKNOWN')
            signal = agent.get('signal', 'HOLD')
            conf = f"{agent.get('confidence', 0)}%"
            reason = agent.get('reasoning', '')
        else:
            role = "UNKNOWN"
            signal = "HOLD"
            conf = "0%"
            reason = str(agent)

        # Wrapped Paragraph for reasoning to fit in cell
        reason_para = Paragraph(reason, cell_style)
        
        table_data.append([role, signal, conf, reason_para])

    # Table Styling
    if len(table_data) > 1:
        t = Table(table_data, colWidths=[80, 60, 80, 300])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0f172a")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), font_name), # Apply font to whole table
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('PADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(t)
    else:
        story.append(Paragraph("No data from agents.", normal_style))

    story.append(Spacer(1, 30))
    
    # 5. DISCLAIMER
    story.append(Paragraph("DISCLAIMER: This report was generated by an autonomous AI system for informational purposes only. Do not rely solely on this data for financial decisions.", disclaimer_style))

    try:
        doc.build(story)
        buffer.seek(0)
        return buffer
    except Exception as e:
        print(f"PDF GENERATION ERROR: {e}")
        raise e
